package com.iov42.solutions.core.sdk.model;

/**
 * Publicly available details about a single key, public key and protocol used to generate the public/private pair, used for signing and verification.
 */
public class PublicCredentials {

    /**
     * Base64-encoded string of a public key, generated by the calling client or some 3rd party.
     */
    private String key;

    /**
     * Possible values: "SHA256WithRSA" "SHA256WithECDSA"
     * Protocol that should be used with the provided key.
     */
    private ProtocolType protocolId;

    private PublicCredentials() {
        // needed for Jackson parser
    }

    public PublicCredentials(ProtocolType protocolId, String key) {
        this.key = key;
        this.protocolId = protocolId;
    }

    public String getKey() {
        return key;
    }

    public ProtocolType getProtocolId() {
        return protocolId;
    }
}
